
WITH ALLETAGE as (
        SELECT CONVERT(date,LEI_LEISTUNGSDATUM) as LEI_LEISTUNGSDATUM,
        PER_PERSONENNR,
        ISNULL(LEI_ISTVERRECHENBAR,0) as ARL_ISTVERRECHENBAR,
        (ISNULL(SUM(BUERO.BMDLEASTUNDEN(LEI_ISTZEITEINGABE,LEI_LEIST_MENGE)),0) +0.0) /3600 AS Zeit
        FROM ZLE.LEI_LEISTUNG
        LEFT JOIN BUERO.PER_PERSON ON PER_FIRMENNR = LEI_PER_FIRMENNR AND PER_PERSONENID = LEI_PER_PERSONENID
        INNER JOIN BUERO.MIT_MITARBEITER ON MIT_FIRMENNR = LEI_ORG_MIT_FIRMENNR AND MIT_MITARBEITERID = LEI_ORG_MITARBEITERID AND MIT_BMDUSERID = 'FUC868'
        WHERE LEI_LEISTUNGSSTATUS <> 3
        AND LEI_LEISTUNGSSTATUS <> 5
        AND LEI_ISTSTORNOBUCHUNG <> 1
        AND LEI_ISTAKONTO <> 1
        AND LEI_ISTSPLITTLEISTUNG <> 1
        AND LEI_ISTAKTIV <> 0
        AND LEI_ISTGUTSCHRIFT <> 1
        AND LEI_ISTZEITEINGABE >= 0
        AND LEI_ISTZEITEINGABE <= 1
        AND LEI_TAUSCHART != 1
        AND LEI_ORG_MIT_FIRMENNR = 1
        AND LEI_STORNO_LEISTUNGLFDNR IS NULL
        AND LEI_LEISTUNGSDATUM>DATEADD(day,-250,GETDATE()) --Für Leistung
        GROUP BY CONVERT(date,LEI_LEISTUNGSDATUM), PER_PERSONENNR, LEI_ISTVERRECHENBAR
	),
	EFK as (
		SELECT
		CONVERT(date, ISNULL(EF1_EFK_ERSTELLDATUM,EFK_ERSTELLDATUM)) as LEI_LEISTUNGSDATUM_Beginn, 
		CONVERT(date, ISNULL(EFK_LETZTES_RECHNUNGSDATUM,GETDATE())) as LEI_LEISTUNGSDATUM_Ende, 
		NULL as PER_PERSONENNR,
		'1' as ARL_ISTVERRECHENBAR,
		SUM(ERP_AUFTRAGSMENGE) AS Zeit
		FROM WWS.EFK_ERFASSKOPFWWS
		LEFT JOIN WWS.EF1_V_EFK_ERFASSKOPFWWS ON EF1_EFK_FIRMENNR = EFK_VON_ANGEB_FIRMENNR AND EF1_EFK_ERFASSUNGSKZ = EFK_VON_ANGEB_ERFASSUNGSKZ AND EF1_EFK_ERFASSUNGSNR = EFK_VON_ANGEB_ERFASSUNGSNR
		LEFT JOIN BUERO.PER_PERSON ON PER_FIRMENNR = EFK_AUFTRAGGEBER_FIRMENNR AND PER_PERSONENID = EFK_AUFTRAGGEBER_KLID
		LEFT JOIN WWS.ERP_ERFASSPOSITIONEN ON ERP_FIRMENNR = EFK_FIRMENNR AND ERP_ERFASSUNGSKZ = EFK_ERFASSUNGSKZ AND ERP_ERFASSUNGSNR = EFK_ERFASSUNGSNR
		INNER JOIN BUERO.MIT_MITARBEITER ON MIT_FIRMENNR = EFK_V1_FIRMENNR AND MIT_MITARBEITERID = EFK_V1_MITARBEITERID AND MIT_BMDUSERID = 'FUC868'
		WHERE EFK_V1_FIRMENNR=1
		AND EFK_RECHNUNGSFREIGABE <> 1
		AND EFK_FERTIGKZ <> 2
		AND ERP_FERTIGKZ <> 2
		AND EFK_ERFASSUNGSKZ = 'IND'
		AND EFK_ERFASSUNGSART <> 'ANG'
		AND PER_ENTSPRICHT_FIRMENNR IS NULL --Aufträge welche an andere Firmen verrechnet werden herausnehmen. Wird normalerweise in eigentlicher Firma ebenso verrechnet.
		AND EFK_ERSTELLDATUM>DATEADD(day,-250,GETDATE())--Für Leistung
		GROUP BY CONVERT(date, ISNULL(EF1_EFK_ERSTELLDATUM,EFK_ERSTELLDATUM)), CONVERT(date, ISNULL(EFK_LETZTES_RECHNUNGSDATUM,GETDATE()))
	),
	NichtVerrechenbar as (
		SELECT LEI_LEISTUNGSDATUM, SUM(Zeit) as NichtVerrZeit 
		FROM ALLETAGE
		WHERE PER_PERSONENNR<>'298200'
		AND ARL_ISTVERRECHENBAR='0'
		GROUP BY LEI_LEISTUNGSDATUM
	),
	NLZ as (
		SELECT LEI_LEISTUNGSDATUM, SUM(Zeit) as NlzZeit
		FROM ALLETAGE
		WHERE PER_PERSONENNR='298200'
		GROUP BY LEI_LEISTUNGSDATUM
	),
	Verrechenbar as (
		SELECT LEI_LEISTUNGSDATUM, SUM(Zeit) as VerrZeit 
		FROM ALLETAGE
		WHERE PER_PERSONENNR<>'298200'
		AND ARL_ISTVERRECHENBAR='1'
		GROUP BY LEI_LEISTUNGSDATUM
	),
	EfkPerH as (
		SELECT LEI_LEISTUNGSDATUM_Beginn, LEI_LEISTUNGSDATUM_Ende, AVG(Zeit)/SUM(NichtVerrechenbar.NichtVerrZeit) as EfkPerH
		FROM EFK
		LEFT JOIN NichtVerrechenbar ON LEI_LEISTUNGSDATUM BETWEEN LEI_LEISTUNGSDATUM_Beginn AND LEI_LEISTUNGSDATUM_Ende
		GROUP BY LEI_LEISTUNGSDATUM_Beginn, LEI_LEISTUNGSDATUM_Ende
	),
	EfkPerTag as (
		SELECT LEI_LEISTUNGSDATUM, AVG(EfkPerH)*SUM(NichtVerrechenbar.NichtVerrZeit) as EfkZeit
		FROM EfkPerH
		LEFT JOIN NichtVerrechenbar ON LEI_LEISTUNGSDATUM BETWEEN LEI_LEISTUNGSDATUM_Beginn AND LEI_LEISTUNGSDATUM_Ende
		GROUP BY LEI_LEISTUNGSDATUM
	)
SELECT *
FROM (
    SELECT DISTINCT FORMAT(ISNULL(ALLETAGE.LEI_LEISTUNGSDATUM,GETDATE()),'yyyyMMdd') as LEI_LEISTUNGSDATUM, 
    ISNULL(NlzZeit,0) as NlzZeit,
    ISNULL(NichtVerrZeit,0)-ISNULL(EfkZeit,0) as NichtVerrZeit,
    ISNULL(VerrZeit,0) as VerrZeit, 
    ISNULL(EfkZeit,0) as EfkZeit
    FROM ALLETAGE
    LEFT JOIN NichtVerrechenbar ON ALLETAGE.LEI_LEISTUNGSDATUM = NichtVerrechenbar.LEI_LEISTUNGSDATUM
    LEFT JOIN Verrechenbar ON ALLETAGE.LEI_LEISTUNGSDATUM = Verrechenbar.LEI_LEISTUNGSDATUM
    LEFT JOIN NLZ ON ALLETAGE.LEI_LEISTUNGSDATUM = NLZ.LEI_LEISTUNGSDATUM
    LEFT JOIN EfkPerTag ON ALLETAGE.LEI_LEISTUNGSDATUM = EfkPerTag.LEI_LEISTUNGSDATUM
    WHERE ALLETAGE.LEI_LEISTUNGSDATUM>DATEADD(day,-150,GETDATE())
    ) as t
ORDER BY LEI_LEISTUNGSDATUM DESC