SELECT DISTINCT
fkc.[name] as Code,
'' as [Comment],
'' as [Description],
CASE
    WHEN DOMAIN_NAME IS NOT NULL THEN SUBSTRING(DOMAIN_NAME,5,LEN(DOMAIN_NAME))
    WHEN DATA_TYPE IS NOT NULL AND DATA_TYPE='datetime' THEN 'DATE'
	WHEN DATA_TYPE IS NOT NULL AND CHARACTER_MAXIMUM_LENGTH IS NOT NULL THEN CONCAT(DATA_TYPE, ' (', CHARACTER_MAXIMUM_LENGTH,')')
	WHEN DATA_TYPE IS NOT NULL AND NUMERIC_PRECISION IS NOT NULL THEN CONCAT(DATA_TYPE, ' (', NUMERIC_PRECISION,'. ',NUMERIC_SCALE,')')
	WHEN DATA_TYPE IS NOT NULL THEN DATA_TYPE
    ELSE NULL
END as Datentyp
FROM sys.all_columns fkc
LEFT JOIN INFORMATION_SCHEMA.COLUMNS ON fkc.[name]=COLUMN_NAME
WHERE 1=1
AND SUBSTRING(fkc.[name],4,1)='_'
ORDER BY fkc.[name]
