SELECT
SCM_SCRTITEL, PER_NAME, M.SCM_SCRNR
FROM BMDENTW.SCM_SCRMAIN M
LEFT JOIN BUERO.PER_PERSON P ON ( M.SCM_TIC_KUNDE_FIRMENNR = P.PER_FIRMENNR ) AND ( M.SCM_TIC_KUNDE_KLID = P.PER_PERSONENID )
LEFT JOIN BUERO.VP1_V_PER_PERSON VP ON ( M.SCM_PER_FIRMENNR = VP.VP1_PER_FIRMENNR ) AND ( M.SCM_PERSONENID = VP.VP1_PER_PERSONENID )
INNER JOIN BMDENTW.SVA_VIEW_SCR_ANZ_ABH SVA ON ( SVA.SCM_SCRNR=M.SCM_SCRNR )
LEFT JOIN BMDENTW.SVC_VIEW_LASTCHANGE SVC ON ( M.SCM_SCRNR = SVC.SCP_SCRNR )
LEFT JOIN PRODUKTION.PCK_PPS_KAPA P1 ON ( M.SCM_PPSKAPAID = P1.PCK_PPSKAPAID )
LEFT JOIN PRODUKTION.APA_ARBEITSPLAN P2 ON ( P1.PCK_AP_ID = P2.APA_AP_ID )
LEFT JOIN BMD.BMU_BMDUSER U1 ON ( M.SCM_BESITZER_BMDUSERID = U1.BMU_BMDUSERID ) 
LEFT JOIN BMD.BMU_BMDUSER U2 ON ( M.SCM_VERANTW_BMDUSERID = U2.BMU_BMDUSERID )
LEFT JOIN (SELECT DISTINCT TIC_MAIN
FROM BMDENTW.TIM_VIEW_TIC_MERGEREL) TR ON ( M.SCM_SCRNR = TR.TIC_MAIN )
LEFT JOIN BMDENTW.SVN_VIEW_SCR_MITNOTIZ SCN ON ( M.SCM_SCRNR = SCN.SCN_SCRNR )
LEFT JOIN BMDENTW.SVT_VIEW_SCR_MITTESTPROTOKOLL SVT ON ( M.SCM_SCRNR = SVT.SCN_SCRNR )
WHERE M.SCM_SCRNR >= 9000000 AND (M.SCM_SCRSTATUS = 1 OR 1 IS NULL OR (1 = 2 AND M.SCM_SCRSTATUS=3)) AND (M.SCM_SCRKZ = 2 OR 2 IS NULL) AND  ((M.SCM_VERANTW_BMDUSERID IS NULL) OR (M.SCM_BESITZER_BMDUSERID IS NULL)) AND M.SCM_NTCSPAKETNR = 22 AND SCM_SCRTITEL IS NOT NULL
ORDER BY SCM_AENDERUNGSDATUM DESC