SELECT * FROM
(
SELECT Top 5000
SCP_SCRNR AS Ticketnummer,
SCM_SCRTITEL AS Ticketname, 
PER_PERSONENNR AS Kundennr, 
CONCAT(
PER_NAME,
' ',
PER_ZUSATZNAME
) AS Kundenname,
REPLACE(SCM_PERSONENID,'KO2000','') AS Kontaktpersonennummer, 
VP1_PER_GESCHLECHT AS Geschlecht,
VP1_PER_TITEL AS Titel,
VP1_PER_VORNAME AS Vorname,
VP1_PER_NAME AS Ansprechpartner,
VP1_PER_TITEL_HINTEN AS TitelHinten,
VP1_PER_DISPLAY_EMAIL AS Email,
VP1_PER_DISPLAY_TELEFONNR AS Telefonnummer,
CASE WHEN SCM_SCRPROJEKTNR=-1 THEN NULL ELSE SCM_SCRPROJEKTNR END as Projektnr
FROM BMDENTW.SCM_SCRMAIN M 
LEFT JOIN BUERO.PER_PERSON P ON ( SCM_TIC_KUNDE_FIRMENNR = PER_FIRMENNR ) AND ( SCM_TIC_KUNDE_KLID = PER_PERSONENID ) 
LEFT JOIN BUERO.VP1_V_PER_PERSON VP ON ( SCM_PER_FIRMENNR = VP1_PER_FIRMENNR ) AND ( SCM_PERSONENID = VP1_PER_PERSONENID ) 
LEFT JOIN BMDENTW.SVC_VIEW_LASTCHANGE SVC ON ( SCM_SCRNR = SVC.SCP_SCRNR ) 
LEFT JOIN (SELECT DISTINCT TIC_MAIN FROM BMDENTW.TIM_VIEW_TIC_MERGEREL) TR ON ( SCM_SCRNR = TR.TIC_MAIN ) 
WHERE SCM_SCRSTATUS = 1
AND SCM_SCRKZ = 2
AND ( SCM_BESITZER_BMDUSERID = 'fuc868' OR SCM_VERANTW_BMDUSERID = 'fuc868')
	ORDER BY SCM_AENDERUNGSDATUM DESC
) as OffeneTickets

UNION ALL

SELECT * FROM
(
	SELECT TOP 2
	SCP_SCRNR AS Ticketnummer,
	SCM_SCRTITEL AS Ticketname, 
	PER_PERSONENNR AS Kundennr, 
	CONCAT(
	PER_NAME,
	' ',
	PER_ZUSATZNAME
	) AS Kundenname,
	REPLACE(SCM_PERSONENID,'KO2000','') AS Kontaktpersonennummer, 
	VP1_PER_GESCHLECHT AS Geschlecht,
	VP1_PER_TITEL AS Titel,
	VP1_PER_VORNAME AS Vorname,
	VP1_PER_NAME AS Ansprechpartner,
	VP1_PER_TITEL_HINTEN AS TitelHinten,
	VP1_PER_DISPLAY_EMAIL AS Email,
	VP1_PER_DISPLAY_TELEFONNR AS Telefonnummer,
	CASE WHEN SCM_SCRPROJEKTNR=-1 THEN NULL ELSE SCM_SCRPROJEKTNR END as Projektnr
	FROM BMDENTW.SCM_SCRMAIN 
	LEFT JOIN BUERO.PER_PERSON ON ( SCM_TIC_KUNDE_FIRMENNR = PER_FIRMENNR ) AND ( SCM_TIC_KUNDE_KLID = PER_PERSONENID ) 
	LEFT JOIN BUERO.VP1_V_PER_PERSON VP ON ( SCM_PER_FIRMENNR = VP1_PER_FIRMENNR ) AND ( SCM_PERSONENID = VP1_PER_PERSONENID ) 
	LEFT JOIN BMDENTW.SVC_VIEW_LASTCHANGE SVC ON ( SCM_SCRNR = SVC.SCP_SCRNR ) 
	LEFT JOIN (SELECT DISTINCT TIC_MAIN FROM BMDENTW.TIM_VIEW_TIC_MERGEREL) TR ON ( SCM_SCRNR = TR.TIC_MAIN ) 
	WHERE SCM_SCRSTATUS = 3
	AND SCM_SCRKZ = 2
	AND ( SCM_BESITZER_BMDUSERID = 'fuc868' OR SCM_VERANTW_BMDUSERID = 'fuc868')
	ORDER BY SCM_AENDERUNGSDATUM DESC
) as GeschlosseneTickets


