SELECT REPLACE(TABLE_SCHEMA,';',',') as TABLE_SCHEMA, REPLACE(TABLE_NAME,';',',') as TABLE_NAME, REPLACE(REPLACE(REPLACE(ISNULL([definition],VIEW_DEFINITION),';',','), char(10), char(32)), char(13), char(32)) as VIEW_DEFINITION
FROM INFORMATION_SCHEMA.VIEWS 
LEFT JOIN sys.sql_modules ON  [definition] LIKE CONCAT('CREATE VIEW ',TABLE_SCHEMA,'.',TABLE_NAME,'%')
WHERE TABLE_SCHEMA<>'dbo'
ORDER BY TABLE_SCHEMA, TABLE_NAME
